# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Java

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
      - reopened
    paths:
      - docs/src/spec.yaml
      - java/**
      - .github/workflows/java.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  linux-build:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    strategy:
      matrix:
        java-version: [ 17 ]
    steps:
      - name: Checkout lance-namespace repo
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}
          cache: "maven"
      - name: Check code style
        working-directory: java
        run: make check
      - name: Running build with Java ${{ matrix.java-version }}
        working-directory: java
        run: make build
